# configure Starship prompt

# Prompt
scan_timeout = 100
prompt_order = [
    "battery",
    "time",
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "kubernetes",
    "docker_context",
    "package",
    "nodejs",
    "ruby",
    "python",
    "conda",
    "rust",
    "golang",
    "java",
    "julia",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    "nim",
    "ocaml",
    "php",
    "terraform",
    "crystal",
    "zig",
    "purescript",
    "nix_shell",
    "aws",
    "memory_usage",
    "env_var",
    "cmd_duration",
    "custom",
    "line_break",
    "jobs",
    "character",
]

# AWS
[aws]
disabled = true

# Battery
[battery]
disabled = false
full_symbol = "Ôï∏"
charging_symbol = "ÔñÉ"
discharging_symbol = "ÔñÇ"
unknown_symbol = "Ôñê"
empty_symbol = "Ôñç"

[[battery.display]]
threshold = 25
style = "bold #FF0A00"

[[battery.display]]
threshold = 99
style = "bold #F86201"



# Character
[character]
symbol = "Œ∂"
use_symbol_for_status = true

# Command Duration
[cmd_duration]
min_time = 3000

# Conda
[conda]
symbol = "Conda "

# Crystal
[crystal]
disabled = true

# Directory
[directory]
truncation_length = 5

# Docker Context
[docker_context]
disabled = false

# Dotnet
[dotnet]
disabled = true

# Elixir
[elixir]
disabled = true

# Elm
[elm]
disabled = true

# Environmnet Variable
[env_var]
disabled = false

# Erlang
[erlang]
disabled = true

# Hostname
[hostname]
prefix = "‚ü™"
suffix = "‚ü´"

# Jobs
[jobs]
symbol = "üåü"

# Kubernetes
[kubernetes]
disabled = false

# Line Break
[line_break]
disabled = false

# Memory Usage
[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = -1
symbol = "Ô°ö "
separator = "~"
style = "bold #B26FCB"

# Mercurial Branch
[hg_branch]
disabled = true

# Nim
[nim]
disabled = true

# Nix-shell
[nix_shell]
disabled = false
use_name = true
symbol = "‚òÉÔ∏è"

# Package Version
[package]
disabled = false
display_private = true

# Ocaml
[ocaml]
disabled = true

# PHP
[php]
disabled = true

# Python
[python]
disabled = false
pyenv_version_name = true

# Singularity
[singularity]
disabled = true

# Terraform
[terraform]
disabled = true

# Time
[time]
disabled = false
format = "%T"

# Username
[username]
disabled = false
show_always = false

# Zig
[zig]
disabled = true

# PureScript
[purescript]
disabled = true
